# fly.toml app configuration file generated for carpoolingreservas on 2024-11-28T07:18:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'carpoolingreservas'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
